### ISSUE TITLE
#/task/BE-Criar novo campo de image do perfil do usuário

### ISSUE THREAD

**Issue by SidneyAfonseca** [webacademyufam/hands-on-t2-01-hobbysphere#140]

**Comment by crislancruz** [comment]
Campo criado e ajustado nas demais rotinas:

![Image](https://github.com/webacademyufam/hands-on-t2-01-hobbysphere/assets/101460092/4c3b4cae-2976-4503-9492-fd859c2d4b9d)

![Image](https://github.com/webacademyufam/hands-on-t2-01-hobbysphere/assets/101460092/93255d85-9c58-4617-a312-a1149bdb6f56)
