### ISSUE TITLE
#/task/BE-Criar tabela para marcar hobbies favoritos por usuario

### ISSUE THREAD

**Issue by SidneyAfonseca** [webacademyufam/hands-on-t2-01-hobbysphere#96]

**Comment by crislancruz** [comment]
**Criada Tabela e endpoints**

- [x] index
- [x] read
- [x] indexUserFavHashtagsByUserId
- [x] indexUserFavHashtagsByHashtagId
- [x] create
- [x] remove



**Realizada documentação no Swagger**

![Image](https://github.com/webacademyufam/hands-on-t2-01-hobbysphere/assets/101460092/9c63a8d5-cd18-405a-8042-02eaa7312cc9)
