### ISSUE TITLE
#/task/BE-Criar função para adicionar e remover hobbies favoritos de usuario

### ISSUE THREAD

**Issue by SidneyAfonseca** [webacademyufam/hands-on-t2-01-hobbysphere#97]

**Comment by crislancruz** [comment]
Funções associadas, incluídas nos endpoints:


**Criada Tabela e endpoints**

- [x] index
- [x] read
- [x] indexUserFavHashtagsByUserId
- [x] indexUserFavHashtagsByHashtagId
- [x] create
- [x] remove



**Realizada documentação no Swagger**

![Image](https://github.com/webacademyufam/hands-on-t2-01-hobbysphere/assets/101460092/3153db7e-94fd-4c6a-9bc1-fc976ec9874b)
